### ISSUE TITLE
docs: guide `fetch-depth`

### ISSUE THREAD

**Issue by jjangga0214** [jjangga0214/haetae#110]
https://github.com/actions/checkout

```yaml
- uses: actions/checkout@v3
  with:
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: 0
```
